### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by turtNova** [thecodefan/Etch-a-Sketch#1]
pls mr tgf add some more features such as:
Color Picker
Click to Paint
Customizable Squares

**Comment by thecodefan** [comment]
sure, gimme 2-3 days

**Comment by thecodefan** [comment]
sure gimme 2-3 days

**Comment by thecodefan** [comment]
color picker, random color is added. click to paint couldn't be implemented so far, but i've added the ability to press S on keyboard to stop colors from filling, it should work as a stopgap measure for now.
